"""create test_switch table

Revision ID: 58adc2729a9c
Revises: 57f4c30b0ad4
Create Date: 2017-02-07 19:43:48.150528

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '58adc2729a9c'
down_revision = '57f4c30b0ad4'
branch_labels = ('haas.ext.switches.test',)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_switch',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hostname', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['switch.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_switch')
    # ### end Alembic commands ###
